### PR TITLE
Update for python3

### PR DESCRIPTION
**Pull request by andor-pierdelacabeza**
I've found unpushed doesn't work using python3, so I've modified a some lines for making it work.

Basically:
- A bunch of print()'s
- A type correction for startswith

Also I've located some things that need some work, as 'locate' and 'svn' detection. Some colour here and there might be nice.

Thx

### CODE REVIEW

**Comment by nailgun** [comment]
Thank you! Merged.

**Comment by andor-pierdelacabeza** [comment]
You're welcome!

Hopefully I'll be sending you some other updates.
Does pypi package repo update automatically?

**Comment by nailgun** [comment]
Not for now. But i'm going to add it to Travis, so it will be automatic.

**Comment by nailgun** [comment]
pypi package updated

**Pull request merged**
